[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.18"
via_ir = true
optimizer_runs = 2000

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@tokenized-strategy/=lib/tokenized-strategy/src/",
    "@periphery/=lib/tokenized-strategy-periphery/src/",
    "@uniswap/v3-core/=lib/uniswap-v3-core/",
    "@uniswap-v3-core/=lib/uniswap-v3-core/contracts/",
    "@uniswap-v3-periphery/=lib/uniswap-v3-periphery/contracts/",
    'src/=src/',
]

[fuzz]
runs = 1000
max_test_rejects = 1_000_000
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
